from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import Billing
from patients.models import Patient
from appointments.models import Appointment
from django.http import HttpResponse
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import cm

@login_required
def billing_list(request):
    query = request.GET.get('q', '')
    status_filter = request.GET.get('status', '')
    billings = Billing.objects.all().order_by('-created_at')
    if query:
        billings = billings.filter(patient__full_name__icontains=query)
    if status_filter:
        billings = billings.filter(status=status_filter)
    return render(request, 'billing/list.html', {
        'billings': billings,
        'query': query,
        'status_filter': status_filter,
    })

@login_required
def billing_add(request):
    if request.method == 'POST':
        Billing.objects.create(
            patient_id=request.POST['patient_id'],
            appointment_id=request.POST['appointment_id'] or None,
            amount=request.POST['amount'],
            status=request.POST['status'],
        )
        messages.success(request, 'Bill added successfully!')
        return redirect('billing_list')
    patients = Patient.objects.all()
    appointments = Appointment.objects.all()
    return render(request, 'billing/add.html', {
        'patients': patients,
        'appointments': appointments,
    })

@login_required
def billing_edit(request, pk):
    billing = get_object_or_404(Billing, pk=pk)
    if request.method == 'POST':
        billing.patient_id = request.POST['patient_id']
        billing.appointment_id = request.POST['appointment_id'] or None
        billing.amount = request.POST['amount']
        billing.status = request.POST['status']
        billing.save()
        messages.success(request, 'Bill updated successfully!')
        return redirect('billing_list')
    patients = Patient.objects.all()
    appointments = Appointment.objects.all()
    return render(request, 'billing/edit.html', {
        'billing': billing,
        'patients': patients,
        'appointments': appointments,
    })

@login_required
def billing_delete(request, pk):
    billing = get_object_or_404(Billing, pk=pk)
    billing.delete()
    messages.success(request, 'Bill deleted!')
    return redirect('billing_list')
def billing_invoice(request, pk):
    billing = get_object_or_404(Billing, pk=pk)

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'filename="invoice_{billing.pk}.pdf"'

    doc = SimpleDocTemplate(response, pagesize=A4)
    styles = getSampleStyleSheet()
    elements = []

    # Header
    elements.append(Paragraph("HOSPITAL MANAGEMENT SYSTEM", styles['Title']))
    elements.append(Paragraph("Official Payment Invoice", styles['Heading2']))
    elements.append(Spacer(1, 0.5*cm))

    # Invoice details table
    invoice_data = [
        ['Invoice #', str(billing.pk)],
        ['Date', billing.created_at.strftime('%d %B %Y')],
        ['Patient', str(billing.patient)],
        ['Appointment', str(billing.appointment) if billing.appointment else 'N/A'],
        ['Amount', f'KES {billing.amount}'],
        ['Status', billing.status.upper()],
    ]

    table = Table(invoice_data, colWidths=[5*cm, 10*cm])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#1a3c5e')),
        ('TEXTCOLOR', (0, 0), (0, -1), colors.white),
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 11),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('PADDING', (0, 0), (-1, -1), 10),
        ('ROWBACKGROUNDS', (1, 0), (1, -1), [colors.HexColor('#f0f4f8'), colors.white]),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cccccc')),
        ('ROUNDEDCORNERS', [4, 4, 4, 4]),
    ]))
    elements.append(table)
    elements.append(Spacer(1, 1*cm))

    # Status color message
    if billing.status == 'paid':
        status_msg = "✓ PAYMENT RECEIVED — Thank you!"
        status_color = '#28a745'
    else:
        status_msg = "⚠ PAYMENT PENDING — Please settle this invoice."
        status_color = '#dc3545'

    elements.append(Paragraph(
        f'<font color="{status_color}"><b>{status_msg}</b></font>',
        styles['Normal']
    ))
    elements.append(Spacer(1, 1*cm))
    elements.append(Paragraph("Generated by Hospital Management System", styles['Normal']))

    doc.build(elements)
    return response